### PR TITLE
style: improve module structure

### PR DESCRIPTION
**Pull request by jannisborn**

### CODE REVIEW

**Comment by drugilsberg** [comment]
@jannisborn not super sure encapsulating two levels of utils is the way to go here.

**Comment by jannisborn** [comment]
@drugilsberg we have the same structure in the other repos (e.g. predictor and omics). I added a `__init__.py` file to the `utils` folder, kin this way the imports are more flexible.

**Review by drugilsberg — CHANGES_REQUESTED** [review]
The `utils/__init__.py` is better. Renaming `utils.py` to `core.py` would be the best l. In any case, we should properly replace all the `utils.utils` imports accordingly.

**Review by drugilsberg — CHANGES_REQUESTED** [review]
Looking at the build failure, a change to the `models/__init__.py` is needed as well. Some considerations for a rening to `core.py` apply.

**Comment by drugilsberg** [comment]
@jannisborn Code structure is ok, but make sure the build passes. Just run the `train_vae.py`'s help locally before pushing.

**Review by drugilsberg — APPROVED** [review]
All good. Just remember to tag after the merge.

**Review by jannisborn — COMMENTED** [review]
request approval

**Pull request merged**
